name: surf_flutter_courses_template
description: Our courses' template.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0" # Dart SDK version
  flutter: 3.10.3 # Fixed Flutter version

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - D:/course/flutter/surf-flutter-courses-template/task-10/assets/
  fonts:
    - family: Bear
      fonts:
        - asset: assets/teddy-bear.ttf
    - family: Brush
      fonts:
        - asset: assets/Brushboy.ttf
    - family: Post
      fonts:
        - asset: assets/posteretro.ttf
    - family: Muller
      fonts:
        - asset: assets/muller.ttf